### ISSUE TITLE
P2P v0.5 changelog

### ISSUE THREAD

**Issue by lyulka** [parallelchain-io/parallelchain-protocol#7]
The P2P section of v0.4. is being written to reflect the canonical implementation (`pchain-network` version 0.4.2) after it was rapidly developed, published, and deployed, and as such has many idiosyncrasies.

This issue lists these idiosyncrasies and propose resolutions. These resolutions will be incorporated in a future version of the protocol. Either v0.4.1, or v0.5.

## List of idiosyncrasies

1. GossipSub topics do not have a clear hierarchy. HotStuff-rs `broadcast` messages are published under the “consensus” topic, while `send_to` messages are published under “{destination}”, even though both categories of messages are consensus-related.
2. Kademlia's protocol name and Identify's protocol version is overridden to "pchain_p2p":
    * Kademlia nodes [do not talk](https://docs.rs/libp2p/latest/libp2p/kad/struct.KademliaConfig.html#method.set_protocol_names) to other Kademlia nodes if they don’t have the same protocol name.
    * We can use this mechanism to segregate instances of ParallelChain P2P networks (e.g., Mainnet from Testnet).
    * But:
        1. “pchain_p2p” is too general a name.
        2. protocol version is [not checked](https://github.com/parallelchain-io/pchain-network/blob/90367aa1cd08824197cdf8f7d1d34a9c80661ac4/src/engine.rs#L170) when deciding whether to call `add_address` on Kad upon receiving an Identify message.
3. The message IDs of GossipSub messages are [overridden](https://github.com/parallelchain-io/pchain-network/blob/5b0b2c39234652638efef077ca280a1fcc896e97/src/behaviour.rs#L80) using [message_id_fn](https://docs.rs/libp2p-gossipsub/latest/libp2p_gossipsub/struct.ConfigBuilder.html#method.message_id_fn) to include the topic and use base64url encoding. The purpose of this is unknown.

## Proposed resolutions

**Comment by lyulka** [comment]
@AlvinHon, why is message ID overridden?:

>The message IDs of GossipSub messages are [overridden](https://docs.rs/libp2p-gossipsub/latest/libp2p_gossipsub/struct.ConfigBuilder.html#method.message_id_fn) to include the topic and use base64url encoding. The purpose of this is unknown.

**Comment by AlvinHon** [comment]
> @AlvinHon, why is message ID overridden?:
> 
> > 3. The message IDs of GossipSub messages are [overridden](https://github.com/parallelchain-io/pchain-network/blob/5b0b2c39234652638efef077ca280a1fcc896e97/src/behaviour.rs#L80) using [message_id_fn](https://docs.rs/libp2p-gossipsub/latest/libp2p_gossipsub/struct.ConfigBuilder.html#method.message_id_fn) to include the topic and use base64url encoding. The purpose of this is unknown.

It is just a stricter rule to filter duplicated message in Gossipsub. The default one is concatenation of source id and sequence number. These two fields could be `None` in the libp2p implementation. Besides, the sequence number is random number but not sequential number. It seems uncomfortable in using the default one.

**Comment by lyulka** [comment]
@AlvinHon

> These two fields could be None in the libp2p implementation.

By default, these fields should be `Some`. I believe that `message_id_fn` sets how the peer itself sets message IDs. If, say, another peer sets an unacceptable message ID for its messages (e.g., it's missing a source ID and a sequence number), then I guess we should reject it.

Whatever the case, I imagine the policy of whether we reject a message or not is not set by `message_id_fn`, but some other function or API in rust-libp2p.

> Besides, the sequence number is random number but not sequential number.

Even with random numbers, message ID collisions should not be a problem since old messages will almost certainly have been removed from every peer's cache by the time the same number is randomly drawn to be the sequence number.

Additionally, based on what I'm seeing, we are just using [whatever sequence number](https://github.com/parallelchain-io/pchain-network/blob/5b0b2c39234652638efef077ca280a1fcc896e97/src/behaviour.rs#L72) GossipSub picks to put it in the overridden message ID, so I don't see how overriding message ID in this manner helps prevent collision.

Overall, I do not yet see the utility of overriding the default. Unless someone can provide more clarification about the purpose of overriding it, I will remove this in the next breaking update to the P2P spec.

**Comment by lyulka** [comment]
@AlvinHon I will be removing [the requirement](https://github.com/parallelchain-io/parallelchain-protocol/blob/d4b7efc428204a73a8761d8f9c00b39d7994c804/P2P.md?plain=1#L55) to override message ID from version 0.4 of the P2P chapter.

Since this is a *relaxation* of the protocol (removing of a requirement), existing implementations that do override message ID are still considered to correctly implement the protocol.

**Comment by lyulka** [comment]
Merged into #8.
